# Site settings
title: Chase Mathis
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chasehmathis.github.io/"

# User settings
username: Chase Mathis
user_description: Researcher
user_title: Undergraduate @ Duke Univeristy
email: chase1mathis@gmail.com
twitter_username: chasemathis29
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: chasehmathis
github_username:  chasehmathis
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

